config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post '/email_recipient', to: 'oauth_callbacks#email_recipient'
  end

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      patch 'reset'
    end
  end

  concern :commentable do
    member do
      patch 'add_comment'
      delete 'delete_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'select', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  get 'user/:id', to: 'users#show_rewards', as: 'user_show_rewards'

  delete 'attachments/:id/purge', to: 'attachments#purge', as: 'purge_attachment'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy, inverse_of: :question
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions
  has_one :reward, dependent: :destroy, as: :rewardable

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  has_many_attached :files

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  validates :title, :body, :author_id, presence: true

  scope :last_day_questions, -> { where('created_at > ?', 1.day.ago) }
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question, serializer: QuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.build(question_params)
    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :bad_request
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :accepted
    else
      render json: { errors: @quetion.errors }, status: :bad_request
    end
  end

  def destroy
    if @question.destroy
      head :accepted
    else
      render json: { errors: @question.errors }
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :author_id,
                                     links_attributes: %i[id name url _destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show destroy update giving_reward publish_question]
  before_action :find_questions, only: %i[index update]
  after_action :publish_question, only: %i[create]

  authorize_resource

  def index; end

  def new
    @question = Question.new
    @question.links.build
    @question.build_reward
  end

  def create
    @question = Question.new(question_params)
    @question.update(author_id: current_user.id)
    if @question.save
      current_user.subscriptions.create(question: @question)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
    @answer.links.build
    gon.question_id = @question.id

    if @question.best_answer_id
      @best_answer = @question.best_answer
      @answers = @question.answers.where.not(id: @question.best_answer_id)
    else
      @answers = @question.answers
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'The question successfully deleted.'
  end

  def update
    @question.update(question_params)
  end

  def giving_reward(answer); end

  private

  def question_params
    params.require(:question).permit(:title, :body, :author_id,
                                     files: [],
                                     links_attributes: %i[id name url _destroy],
                                     reward_attributes: %i[name image])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def find_questions
    @questions = Question.all
  end

  def publish_question
    return if @question.errors.any?

    vote_hash = Hash[
      like_url: like_question_url(@question),
      dislike_url: dislike_question_url(@question),
      reset_url: reset_question_url(@question)
    ]

    attached_files = @question.files&.map do |file|
      {
        file_name: file.filename.to_s,
        file_url: url_for(file)
      }
    end

    links = @question.links&.map do |link|
      if link.gist?
        {
          link_id: link.id,
          gist_id: link.give_gist_id
        }
      else
        {
          link_id: link.id,
          link_url: link.url,
          link_name: link.name
        }
      end
    end

    if @question.reward
      reward = {
        reward_name: @question.reward.name,
        reward_url: url_for(@question.reward.image)
      }
    end

    ActionCable.server.broadcast 'questions_channel',
                                 {
                                   question: { id: @question.id,
                                               vote_rank: Vote.rank_of_votable(@question),
                                               body: @question.body,
                                               title: @question.title,
                                               question_url: question_url(@question),
                                               author_email: @question.author.email,
                                               user_signed_in: "#{current_user ? true : false}",
                                               vote: vote_hash,
                                               attachments: attached_files,
                                               links: links,
                                               reward: reward }
                                 }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, local:true do |f|
  p 
    = f.label :title
    = f.text_field :title 
  p 
    = f.label :body 
    = f.text_field :body 
  p 
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p 
    = f.fields_for :reward do |r|
      p 
        = r.label :name, 'Reward name'
        = r.text_field :name
      p 
        = r.label :image 
        = r.file_field :image, direct_upload: true
  
  = render 'shared/links_form', f: f 

  p = f.submit 'Ask'

app/views/questions/_question.html.slim
.question-errors.raw
    = render 'shared/errors', resource: question  	
.question.card.text-center id="#{question.id}"
  .question-main.raw
    .question-vote.col.col-md-2
      .votable-rank id="#{question.id}" 
        = Vote.rank_of_votable(question)	
      .voting
        = render 'shared/vote', votable: question
    - cache question do 
      .question-content.col.col-md-6
        p  #{question.body}
        h6  #{question.title} 

    .question-actions.col.col-md-2
      p = link_to 'Show', question_path(question) 
      - if can?(:update, question)
        - unless action_name == "show"
          p = link_to  "Delete", question_path(question), method: :delete
        p = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    
    .question-author.col.col-md-2 
      = User.find(question.author_id).email

  .question-edit-form.card
    = form_with model: question, local:false, class: 'hidden', html: { id: "edit-question-#{question.id}"} do |f|
      p 
        = f.label :title
        = f.text_field :title 
      p 
        = f.label :body 
        = f.text_field :body 
      p 
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
      p = f.submit 'Save'

      = render 'shared/links_form', f: f

  .question-nested.raw.fs-6.lh-1
    = render 'shared/show_nested_attributes', resource: question
  

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  - if can?(:create,Question)
    p= link_to 'Ask question', new_question_path 
  .questions-list.question-edit-hide-form   
    = render @questions 

app/views/questions/new.html.slim
=render 'shared/errors', resource: @question

=render 'form'

app/views/questions/show.html.slim
.question-edit-hide-form  
  .question-show-content id="#{@question.id}"
    = render 'questions/question', question: @question

  - if current_user 
    .question-subscription id="question-#{@question.id}"
      =render 'shared/subscription',
      resource: @question,
      subscription: current_user.subscriptions.find_by(question: @question)

  - cache [@question, 'comment']
    .question-comments id="#{class_by_string(@question)}-#{@question.id}"
        .comments-list 
          = render 'comments/list', commentable: @question
        .new-comment
          = render 'comments/form', commentable: @question

    .question-reward
      = render 'shared/reward_link', resource: @question
        
  - cache ['answers', @question]
    .answers.card.text-center
      h2 Answers:
      .answer-errors
        = render 'shared/errors', resource: @answer
      - if @best_answer
        .best-answer.border.border-primary
          = render 'answers/answer', answer: @best_answer 
      .other-answers 
        = render partial:'answers/answer', collection: @answers

      - if user_signed_in?  
        = render 'answers/form'

app/views/questions/update.js.erb
$('.question-errors').html("<%= render 'shared/errors', resource: @question %>");

<% if !@question.errors.present? %>
  $('.questions-list').html('<%= j render @questions %>');
<% end %>