config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post '/email_recipient', to: 'oauth_callbacks#email_recipient'
  end

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      patch 'reset'
    end
  end

  concern :commentable do
    member do
      patch 'add_comment'
      delete 'delete_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'select', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  get 'user/:id', to: 'users#show_rewards', as: 'user_show_rewards'

  delete 'attachments/:id/purge', to: 'attachments#purge', as: 'purge_attachment'

  mount ActionCable.server => '/cable'
end

app/views/shared/_attachment.html.slim
 -if resource.files.attached?
  .col.col-2
    p Attachments:
  .col
    - resource.files.each do |file|
      p = link_to file.filename.to_s, url_for(file)
      - if current_user && current_user.author?(resource)
        p = link_to  "Remove file", purge_attachment_path(file), method: :delete 

app/views/shared/_errors.html.slim
-if resource.errors.present?
  b= "#{resource.errors.count} errors detected: "
  ul 
    -resource.errors.full_messages.each do |message|
      li= message 

app/views/shared/_link_fields.html.slim
.nested-fields 
  p 
    = f.label :name, 'Link name'
    = f.text_field :name
  p 
    = f.label :url
    = f.text_field :url
  = link_to_remove_association 'remove link', f

app/views/shared/_links_form.html.slim
#links
  = f.fields_for :links do |link|
    = render 'shared/link_fields', f: link
  .links
    = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

app/views/shared/_navbar.html.slim
nav class="navbar navbar-expand-lg bg-body-tertiary" 
  div class="container-fluid" 
    div class="navbar-collapse" id="navbarNav"
      ul class="navbar-nav"
        li class="nav-item" 
          = link_to 'Questions', questions_path, class: "nav-link", "aria-current" => "page"
        li class="nav-item"
          = link_to 'Signup', new_user_registration_path, class: "nav-link", "aria-current" => "page"
        li class="nav-item"
          = link_to 'Login', new_user_session_path, class: "nav-link", "aria-current" => "page"
    div class="search col.col-md-2"
      .container       
        = form_with url:'/search', method: :get do |f| 
          span Find in
          = f.select :search_area, [:question, :answer, :comment, :user, :all]
          = f.text_field :query
          = f.submit 'Find'
- if user_signed_in?
  = "Hello, #{ current_user.email } || "
  = link_to  "Log out", destroy_user_session_path, method: :delete
  p = link_to "#{current_user.email} rewards", user_show_rewards_path(current_user)

app/views/shared/_reward_link.html.slim
-if resource.reward.present?
    p = link_to resource.reward.name, url_for(resource.reward.image)

app/views/shared/_show_links.html.slim
-if resource.links.present?
  p Links: 
  - resource.links.each do |lnk|
    - if lnk.gist?  
      p = link_to 'Show gist content', '#', class: "show-gist-trigger links",
        data: {gist_id: lnk.give_gist_id, link_id: lnk.id } 
      .gist-content.links id="#{lnk.id}"
    - else 
      = link_to lnk.name, lnk.url, class: 'links', id:lnk.id

app/views/shared/_show_nested_attributes.html.slim
div class="#{class_by_string(resource)}-links" id="#{resource.id}"
  = render "shared/show_links", resource: resource
div class="#{class_by_string(resource)}-attachments" id="#{resource.id}"
  = render "shared/attachment", resource: resource 

app/views/shared/_subscription.html.slim
-if subscription && subscription.user == subscription.question.author
  p = link_to 'Unsubscribe', question_subscription_path(resource, subscription), remote: true,
      method: :delete, class: 'btn btn-danger', data: { type: :js }  
-else
  p = link_to 'Subscribe', question_subscriptions_path(resource), remote: true,
      method: :post, class: 'btn btn-success' , data: { type: :js }  

app/views/shared/_vote.html.slim
- if current_user && !current_user.author?(votable)
	.votable-vote
	- if current_user.can_vote_for?(votable)
			= link_to  like_question_path(votable), class: 'like vote-link',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					 <i class="bi bi-hand-thumbs-up"></i>
			= link_to  dislike_question_path(votable), class: 'dislike vote-link',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					 <i class="bi bi-hand-thumbs-down"></i>
			= link_to reset_question_path(votable), class: 'reset vote-link hidden',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json },  remote: true do 
					 <i class="bi bi-x-circle"></i>	
	- else         
			= link_to  like_question_path(votable), class: 'like vote-link hidden',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					<i class="bi bi-hand-thumbs-up"></i>
			= link_to  dislike_question_path(votable), class: 'dislike vote-link hidden',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					<i class="bi bi-hand-thumbs-down"></i>
			= link_to reset_question_path(votable), class: 'reset vote-link',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json },  remote: true do 
					<i class="bi bi-x-circle"></i>

app/views/shared/_vote_answer.html.slim
- if can?(:like, votable) 
	.votable-vote
	- if current_user.can_vote_for?(votable)
			= link_to url_for([:like, votable]),
       class: 'like vote-link', id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
			   <i class="bi bi-hand-thumbs-up"></i>
			= link_to  url_for([:dislike, votable]), class: 'dislike vote-link',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					 <i class="bi bi-hand-thumbs-down"></i>
			= link_to url_for([:reset, votable]), class: 'reset vote-link hidden',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json },  remote: true do 
					 <i class="bi bi-x-circle"></i>	
	- else         
			= link_to  url_for([:like, votable]), class: 'like vote-link hidden',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					<i class="bi bi-hand-thumbs-up"></i>
			= link_to  url_for([:dislike, votable]), class: 'dislike vote-link hidden',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json }, remote: true do 
					<i class="bi bi-hand-thumbs-down"></i>
			= link_to url_for([:reset, votable]), class: 'reset vote-link',
					id: votable.id, method: :patch, data: { id: votable.id, type: :json },  remote: true do 
					<i class="bi bi-x-circle"></i>