config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post '/email_recipient', to: 'oauth_callbacks#email_recipient'
  end

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      patch 'reset'
    end
  end

  concern :commentable do
    member do
      patch 'add_comment'
      delete 'delete_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'select', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  get 'user/:id', to: 'users#show_rewards', as: 'user_show_rewards'

  delete 'attachments/:id/purge', to: 'attachments#purge', as: 'purge_attachment'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :body, :question_id, :author_id, presence: true

  after_create :notify_subscribers

  def mark_as_best
    question.update(best_answer_id: id)
    GivingReward.create(reward_id: question.reward.id, user_id: author.id) if question.reward.present?
  end

  def is_best?
    question.best_answer_id == id
  end

  private

  def notify_subscribers
    NotifySubscribersJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: :show
  before_action :find_answer, only: %i[show destroy update select]
  before_action :find_question_by_id, only: :create
  before_action :find_question, only: %i[destroy show update select]
  after_action :publish_answer, only: %i[create]

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.update(author_id: current_user.id)

    respond_to do |format|
      if @answer.save
        format.html { render @answer }
      else
        format.html { render partial: 'shared/errors', locals: { resource: @answer }, status: '422' }
      end
    end
  end

  def show; end

  def destroy
    @answer.destroy
    redirect_to question_path(@question), notice: 'The answer deleted successfully.'
  end

  def update
    @answer.update(answer_params)
    @best_answer = @question.best_answer
    @other_answers = @best_answer ? @question.answers.where.not(id: @best_answer.id) : @question.answers
  end

  def select
    @answer.mark_as_best
    @best_answer = @answer
    @other_answers = @question.answers.where.not(id: @answer.id)
    flash[:notice] = 'Best answer selected'
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :question_id, :author_id, files: [],
                                                                    links_attributes: %i[id name url _destroy])
  end

  def find_question_by_id
    @question = Question.find(params[:question_id])
  end

  def find_question
    @question = @answer.question
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    vote_hash = Hash[
      like_url: like_answer_url(@answer),
      dislike_url: dislike_answer_url(@answer),
      reset_url: reset_answer_url(@answer)
    ]

    attached_files = @answer.files&.map do |file|
      {
        file_name: file.filename.to_s,
        file_url: url_for(file)
      }
    end

    links = @answer.links&.map do |link|
      if link.gist?
        {
          link_id: link.id,
          gist_id: link.give_gist_id
        }
      else
        {
          link_id: link.id,
          link_url: link.url,
          link_name: link.name
        }
      end
    end

    ActionCable.server.broadcast("question_channel#{@answer.question.id}",
                                 {
                                   answer: { id: @answer.id,
                                             vote_rank: Vote.rank_of_votable(@answer),
                                             body: @answer.body,
                                             answer_url: answer_url(@answer),
                                             author_email: @answer.author.email,
                                             author_id: @answer.author.id,
                                             user_signed_in: "#{current_user ? true : false}",
                                             vote: vote_hash,
                                             attachments: attached_files,
                                             links: links }
                                 })
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show update destroy]

  authorize_resource

  def index
    @answers = @question.answers
    render json: @answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer, serializer: AnswerSerializer
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.update(author_id: current_user.id)

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :bad_request
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, status: :accepted
    else
      render json: { errors: @answer.errors }, status: :bad_request
    end
  end

  def destroy
    byebug
    if @answer.destroy
      head :accepted
    else
      render json: { errors: @answer.errors }
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:id, :body, :question_id, :author_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer.card id="#{class_by_string(answer)}-#{answer.id}"
  .row 
    .vote-block.col-2
      .votable-rank id="#{answer.id}" 
        = Vote.rank_of_votable(answer)
      = render 'shared/vote_answer', votable: answer
    .answer-content.col.d-flex.flex-row
      .answer-author.text-primary.me-2
        = answer.author.email 
      .answer-content
        = answer.body
    .answer-actions.col-2
      - if can?(:update, answer) 
        p = link_to 'Edit', answer, class: 'edit-answer-link',
          data: { answer_id: answer.id }, remote: true
        p = link_to 'Delete answer', answer_path(answer), class: 'delete-answer-link',
          data: { answer_id: answer.id }, method: :delete, remote: true
      - if can?(:select, Answer) && !answer.is_best?
        p = link_to 'Best answer', select_answer_path(answer),
          class: 'best-answer-link',
          data: { answer_id: answer.id },
          method: :patch,
          remote: true
  .answer-nested.raw.fs-6.lh-1
    = render 'shared/show_nested_attributes', resource: answer

  .answer-edit-form.row
    = render 'answers/form_edit', resource: answer

  .answer-comments.row
    .comments-list 
      = render 'comments/list', commentable: answer
    .new-comment
      = render 'comments/form', commentable: answer

app/views/answers/_best_answer.html.slim
li 
  div class="best_answer-#{@best_answer.id}"
    p= "Best answer: #{@best_answer.body}"

    .best-answer-attachments 
      = render 'shared/attachment', resource: @best_answer

    .best-answer-links 
      = render 'shared/show_links', resource: @best_answer
    
    .best-answer-vote 
      = render 'shared/vote', votable: @best_answer

    -if can?(:update, @best_answer) 
      p = link_to 'Edit answer', @best_answer,
          class: 'edit-answer-link',
          data: { answer_id: @best_answer.id }
      p = link_to 'Delete answer', answer_path(@best_answer),
          class: 'delete-answer-link',
          method: 'delete',
          data: { answer_id: @best_answer.id }
    
    .best-answer-nested.raw.fs-6.lh-1
      = render 'shared/show_nested_attributes', resource: answer

    .best-answer-form-edit
      = render 'answers/form_edit', resource: @best_answer

app/views/answers/_form.html.slim
= form_with model:[@question, @answer], local: false, class: 'new-answer'  do |f|
  p 
    = f.label :body
    = f.text_area :body
  p 
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  = render 'shared/links_form', f: f   

  p = f.submit 'Give answer'

app/views/answers/_form_edit.html.slim
= form_with model: resource , local: false, class: 'hidden', html: { id: "edit-answer-#{resource .id}" } do |f|
    p 
      = f.label :body
      = f.text_area :body
    p   
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
    p = f.submit 'Save'

    = render 'shared/links_form', f: f

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.answers .other-answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if !@answer.errors.present?%>
  $(".answer-<%= @answer.id %>")
<% end %>

app/views/answers/select.js.erb
$('.best-answer').html("<%= j render @best_answer %>")

$('.other-answers').html("<%= j render @other_answers %>")

app/views/answers/show.html.slim
h3 Question id #{@question.id} : #{@question.title} | #{@question.body}
h3 Answer id #{@answer.id} : #{@answer.body}
h3 =link_to  "Delete", answer_path, method: :delete, data: { confirm: 'Are you sure?' }

app/views/answers/update.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if !@answer.errors.present? %>
  <% if @best_answer%>
    $('.best-answer').html('<%= j render @best_answer %>');
  <% end %>
  $('.other-answers').html('<%= j render @other_answers %>');
<% end %>